### PR TITLE
Upgrade to Quarkus 3.0.0.Final

### LINKED ISSUE #146: Quarkus 3
Quarkus 3 is on the horizon and we should make sure we are compatible. See https://github.com/quarkiverse/quarkiverse/wiki/Migrating-to-Quarkus-3.x for more information on how to migrate.

### PR DESCRIPTION
**Pull request by gsmet**
Fixes #146

### CODE REVIEW

**Comment by gsmet** [comment]
@bpasson it would be nice if we could release a new major version with the Quarkus 3 upgrade before April 25th.

**Comment by bpasson** [comment]
@gsmet working on it. I have a local build that works. Just working out the final kinks. Release will come next week.

**Review by bpasson — APPROVED** [review]
All good @gsmet I'll accept this. one and rebase my own additional changes on top of this to create a final 3.0.0 release.

**Comment by bpasson** [comment]
@all-contributors please add @gsmet for code

**Pull request merged**
