### PR TITLE
Do close Socket used to ping RabbitMQ server

### PR DESCRIPTION
**Pull request by SpeedsterF2**
Do not leak resources.

### CODE REVIEW

**Comment by bpasson** [comment]
Good find, I will review the PR and if all checks out accept it.

**Review by bpasson — CHANGES_REQUESTED** [review]
We should indeed close the socket. The suggested change can be simplified by using the outer try directly as try-with-resources. can you update the PR please.

**Comment by SpeedsterF2** [comment]
> We should indeed close the socket. The suggested change can be simplified by using the outer try directly as try-with-resources. can you update the PR please.

The suggested solution does use try-with-resources.

**Comment by SpeedsterF2** [comment]
> We should indeed close the socket. The suggested change can be simplified by using the outer try directly as try-with-resources. can you update the PR please.



> We should indeed close the socket. The suggested change can be simplified by using the outer try directly as try-with-resources. can you update the PR please.



> We should indeed close the socket. The suggested change can be simplified by using the outer try directly as try-with-resources. can you update the PR please.

Updated the PR.

**Pull request merged**
